name: Train AI on New Data

on:
  push:
    paths:
      - 'Training_Data/**'  # Trigger on any new or modified files in the Training_Data folder
  workflow_dispatch:  # Manual trigger option

jobs:
  validate-train:
    name: Validate and Train AI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download and Prepare Stock Data
        run: |
          python download_and_prepare_stock_data.py

      - name: Format for ALBERT
        run: |
          python format_for_albert.py --folder Training_Data

      - name: Validate and Prepare Data
        run: |
          python validate_and_prepare.py

      - name: Optimize Data for AI Model
        run: |
          python optimize_data.py --input Training_Data/validated_data.csv --output Training_Data/optimized_data.csv

      - name: Train AI Model
        run: |
          python train_model.py

      - name: Save Trained Model
        run: |
          mkdir -p trained_model
          if [ ! -f "trained_model/model_weights.pth" ]; then
            echo "Training did not produce model_weights.pth" >&2
            exit 1
          fi

      - name: Install Hugging Face Hub CLI
        run: |
          pip install huggingface-hub

      - name: Upload model weights to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli login --token $HF_TOKEN
          huggingface-cli upload rmanzo28/Stockai trained_model/model_weights.pth
