name: Time Series Data Pipeline

on:
  push:
    paths:
      - 'Training_Data/**'
  workflow_dispatch:

jobs:
  process-data:
    name: Process and Prepare Time Series Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Step to fetch and prepare time series data
      - name: Fetch and Prepare Time Series Data
        run: |
          python download_and_prepare_stock_data.py

      # Step to format the data for time series processing
      - name: Format for Time Series
        run: |
          python format_for_albert.py --folder Training_Data

      # Step to validate and clean the time series data
      - name: Validate and Clean Data
        run: |
          python validate_and_prepare.py --data-dir Training_Data

      # Step to optimize the data (e.g., feature engineering, normalization)
      - name: Optimize Data for Processing
        run: |
          python optimize_data.py --input Training_Data/validated_data.csv --output Training_Data/optimized_data.csv

      # Optional step: Archive processed data for backup or auditing purposes
      - name: Archive Processed Data
        run: |
          mkdir -p processed_data
          cp Training_Data/optimized_data.csv processed_data/
          echo "Data archived for further use or auditing."

      # Commit the processed data file to the repo using GH_TOKEN for authentication
      - name: Commit Processed Data File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add Training_Data/optimized_data.csv
          git commit -m "Add optimized time series data"
          
          # Authenticate using the GITHUB_TOKEN from GitHub Secrets
          git remote set-url origin https://github.com/${{ github.repository }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

