name: Train AI on New Data

on:
  push:
    paths:
      - 'Training_Data/**'  # Trigger on changes in Training_Data folder
  workflow_dispatch:  # Manual trigger option

jobs:
  validate-train:
    name: Validate and Train AI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate and Prepare Data
        run: |
          python validate_and_prepare.py

      - name: Train AI Model
        run: |
          python train_model.py

      - name: Save Trained Model
        run: |
          mkdir -p trained_model
          # model_weights.pth is already saved by the script, ensure it's there
          if [ ! -f "trained_model/model_weights.pth" ]; then
            echo "Training did not produce model_weights.pth" >&2
            exit 1
          fi

      - name: Upload model weights
        uses: actions/upload-artifact@v4
        with:
          name: model-weights
          path: trained_model/model_weights.pth

      - name: Commit Trained Model
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Updated trained model weights'
          add: 'trained_model/model_weights.pth'
