name: Run Stock Prediction When Input Script Changes

on:
  push:
    paths:
      - 'input.py'
      - '.github/workflows/run-prediction.yml'

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas

    - name: Run input.py to generate input data
      run: |
        python input.py

    - name: Run prediction using generated data
      run: |
        python3 -c "
import pickle
import pandas as pd
from src.models.stock_ai import StockAI  # Adjust if needed

# Load trained model
with open('trained_model/random_forest_model.pkl', 'rb') as f:
    model = pickle.load(f)

# Load generated input data
input_data = pd.read_csv('DATA/input.csv')  # <---- USING DATA IN ALL CAPS NOW, YOU ANIMAL

# Run prediction
if hasattr(model, 'predict'):
    preds = model.predict(input_data)
    print('Predictions:', preds)
else:
    raise AttributeError('Model object does not have a predict() method. You absolute buffoon.')
"
