name: Run Stock Data Prep on Script Edit

on:
  push:
    paths:
      - 'download_and_prepare_stock_data.py'
  pull_request:
    paths:
      - 'download_and_prepare_stock_data.py'
  workflow_dispatch:  # This is the manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run stock data preparation script
        run: |
          python download_and_prepare_stock_data.py

      - name: Commit generated data to Training_Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Training_Data/
          git diff --cached --quiet || git commit -m "Auto-update Training_Data from stock data prep"
          git push
        env:
          # Needed for push permission
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

